server:
  port: 8090
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/africa
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
    initialization-mode: always
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        show_sql: true
        format_sql: true
  data:
    rest:
      basePath: /api
logging:
  level:
    org:
      hibernate:
        type: trace


